### ISSUE TITLE
formatNumber fails when given an object with country and number

### ISSUE THREAD

**Issue by uberchris2** [catamphetamine/libphonenumber-js#208]
We are having the following issue after upgrading from 1.1.11 to 1.2.1:
> Argument of type '{ country: string; phone: any; }' is not assignable to parameter of type 'TelephoneNumber'.

It may be a red herring, but on commit [2f2ff4e3f9e88aa0287bb2fb7f323d8ee10d5879 in index.d.ts line 46](https://github.com/catamphetamine/libphonenumber-js/commit/2f2ff4e3f9e88aa0287bb2fb7f323d8ee10d5879#diff-b52768974e6bc0faccb7d4b75b162c99), the signature for 
`export function formatNumber(countryAndNumber: {country: CountryCode, phone: TelephoneNumber}, format: NumberFormat): string;`
is removed. This seems to break this functionality from the README:
`formatNumber({ country: 'US', phone: '2133734253' }, 'International')`

**Comment by catamphetamine** [comment]
Yes, I removed `countryAndNumber: {country: CountryCode, phone: TelephoneNumber}` because it was copy-pasta.
Why doesn't the default `TelephoneNumber` work?

**Comment by uberchris2** [comment]
Property `country` does not exist on type `TelephoneNumber` because it is defined as
`export interface TelephoneNumber extends String { }`

**Comment by catamphetamine** [comment]
Then it's not `TelephoneNumber`.
Look at `ParsedNumber`.
Why doesn't it work?

**Comment by uberchris2** [comment]
That's a good point, it should be handled by ParsedNumber. In that case I'm not sure exactly how we're getting the error.

FWIW, here's our usage:
 ``` ts
export class PhonePipe implements PipeTransform {
  transform(value): any {
    if (!value) {
      return null;
    }
    return formatNumber({ country: 'US', phone: value.toString() }, 'National');
  }
}
```
And here's our error:

> Object literal may only specify known properties, and 'country' does not exist in type 'TelephoneNumber'.,...FILELOCATION.../src/app/pipes/phone.pipe.ts (14,27): Argument of type '{ country: string; phone: any; }' is not assignable to parameter of type 'TelephoneNumber'.

Reverting to 1.1.11 seemed to fix it for us, but I apparently don't know why.

**Comment by catamphetamine** [comment]
I see, so between these two:

```typescript
export function formatNumber(parsedNumber: ParsedNumber, format: NumberFormat): string;
export function formatNumber(phone: TelephoneNumber, format: NumberFormat): string;
```

It chooses the second one for some reason.
Maybe it thinks all other `ParsedPhone` fields are required.

**Comment by catamphetamine** [comment]
So I googled for a couple of minutes and found out that TypeScript "interface"s properties are required unless a question mark is added.
Try version `1.2.2`.
